import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import StoreProvider from "@/components/provider/redux-provider/StoreProvider";
import { EpubProvider } from "@/context/EpubContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Booksnai",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <EpubProvider>
            <div className="">
              <Navbar />
            </div>
            {/* <div className="flex">
              Side Navbar
              
                <div className="w-44 bg-gray-200 sticky top-0 h-screen overflow-y-auto flex flex-col gap-4">
                  Side Navbar Content 
                   You can add links or any content for your side navbar here
                  <h1>Home</h1>
                  <h1>Home</h1>

                </div>
            
            </div> */}
              <div className="">{children}</div>
            {/* <div>
          <Footer/>
        </div> */}
          </EpubProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
